(() => {
  const API = (window.MRF_API_URL || '').replace(/\/$/, '');
  const tokenKey = 'mrf_admin_token';
  const $ = (id) => document.getElementById(id);
  const escapeHtml = (value = '') => String(value).replace(/[&<>'"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c]));
  const getToken = () => sessionStorage.getItem(tokenKey) || '';
  const setStatus = (id, text, error = false) => { const el = $(id); if (el) { el.textContent = text; el.style.color = error ? '#ff735c' : ''; } };
  const api = async (path, options = {}) => { const headers = { ...(options.body instanceof FormData ? {} : { 'Content-Type': 'application/json' }), ...(options.headers || {}), ...(getToken() ? { Authorization: `Bearer ${getToken()}` } : {}) }; const response = await fetch(`${API}${path}`, { ...options, headers }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || `Request failed (${response.status})`); return data; };
  let library = [];

  function showDashboard() { $('login-panel').hidden = true; $('dashboard').hidden = false; loadDashboard(); }
  function showLogin() { $('dashboard').hidden = true; $('login-panel').hidden = false; }
  function fillEditor(item = {}) { $('content-id').value = item.id || ''; $('content-type').value = item.type || 'video'; $('content-title').value = item.title || ''; $('content-slug').value = item.slug || ''; $('content-image').value = item.image || ''; $('content-url').value = item.video_url || item.url || ''; $('content-category').value = item.category || item.tag || ''; $('content-year').value = item.year || ''; $('content-description').value = item.description || item.excerpt || ''; $('content-published').checked = item.published !== 0; $('editor-title').textContent = item.id ? 'Edit content' : 'New content'; }
  function renderLibrary(type = 'all') { const list = $('content-list'); const items = type === 'all' ? library : library.filter((item) => item.type === type); if (!items.length) { list.innerHTML = '<p class="muted">No items in this view.</p>'; return; } list.innerHTML = items.map((item) => `<article class="content-row"><img class="content-thumb" src="${escapeHtml(item.image || 'assets/doob-poster.jpg')}" alt=""><div><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.type)} · ${item.published ? 'Published' : 'Draft'}</p></div><div class="content-row-actions"><button class="mini-button edit-item" data-id="${item.id}">Edit</button><button class="mini-button delete-item" data-id="${item.id}">Delete</button></div></article>`).join(''); list.querySelectorAll('.edit-item').forEach((button) => button.onclick = () => fillEditor(library.find((item) => item.id === Number(button.dataset.id)))); list.querySelectorAll('.delete-item').forEach((button) => button.onclick = async () => { if (!confirm('Delete this content item?')) return; try { await api(`/api/admin/content/${button.dataset.id}`, { method: 'DELETE' }); await loadContent(); setStatus('content-status', 'Item deleted.'); } catch (error) { setStatus('content-status', error.message, true); } }); }
  function renderModeration(reviews = []) { const container = $('review-list'); if (!reviews.length) { container.innerHTML = '<p class="muted">No reviews need attention.</p>'; return; } container.innerHTML = `<div class="review-moderation">${reviews.map((review) => `<article class="moderation-row"><div><strong>${escapeHtml(review.name)} · ${review.rating}/5</strong><p>${escapeHtml(review.body)}</p></div><div class="mod-actions"><button class="mini-button approve-review" data-id="${review.id}">Approve</button><button class="mini-button delete-review" data-id="${review.id}">Delete</button></div></article>`).join('')}</div>`; container.querySelectorAll('.approve-review').forEach((button) => button.onclick = () => moderateReview(button.dataset.id, true)); container.querySelectorAll('.delete-review').forEach((button) => button.onclick = () => moderateReview(button.dataset.id, false)); }
  async function moderateReview(id, approved) { try { await api(`/api/admin/reviews/${id}`, { method: 'PATCH', body: JSON.stringify({ approved }) }); await loadReviews(); await loadMetrics(); } catch (error) { setStatus('login-status', error.message, true); } }
  async function loadContent() { library = (await api('/api/admin/content')).items || []; renderLibrary(document.querySelector('.tabs button.active')?.dataset.type || 'all'); setStatus('content-status', `${library.length} items in library.`); }
  async function loadReviews() { const data = await api('/api/admin/reviews'); renderModeration(data.reviews || []); }
  async function loadMetrics() { const data = await api('/api/admin/metrics'); $('metric-content').textContent = data.content ?? '—'; $('metric-media').textContent = data.media ?? '—'; $('metric-reviews').textContent = data.pending_reviews ?? '—'; $('metric-rating').textContent = data.average_rating ? Number(data.average_rating).toFixed(1) : '—'; renderMedia(data.media_items || []); }
  function renderMedia(items) { const list = $('media-list'); list.innerHTML = items.slice(0, 20).map((item) => `<a class="media-chip" href="${escapeHtml(item.url || '#')}" target="_blank" rel="noopener">${escapeHtml(item.key)}</a>`).join(''); }
  async function loadDashboard() { try { await Promise.all([loadContent(), loadReviews(), loadMetrics()]); } catch (error) { if (error.message.includes('401')) { sessionStorage.removeItem(tokenKey); showLogin(); setStatus('login-status', 'Session expired. Please sign in again.', true); } else setStatus('content-status', error.message, true); } }
  document.addEventListener('DOMContentLoaded', () => {
    if (getToken()) showDashboard();
    $('login-form').onsubmit = async (event) => { event.preventDefault(); setStatus('login-status', 'Signing in…'); try { const data = await api('/api/admin/login', { method: 'POST', body: JSON.stringify({ username: $('username').value, password: $('password').value }) }); sessionStorage.setItem(tokenKey, data.token); showDashboard(); } catch (error) { setStatus('login-status', 'Invalid credentials or API unavailable.', true); } };
    $('logout').onclick = () => { sessionStorage.removeItem(tokenKey); showLogin(); };
    $('new-content').onclick = () => fillEditor(); $('cancel-edit').onclick = () => fillEditor();
    document.querySelectorAll('#content-tabs button').forEach((button) => button.onclick = () => { document.querySelectorAll('#content-tabs button').forEach((tab) => tab.classList.remove('active')); button.classList.add('active'); renderLibrary(button.dataset.type); });
    $('content-form').onsubmit = async (event) => { event.preventDefault(); const id = $('content-id').value; const payload = { type: $('content-type').value, title: $('content-title').value, slug: $('content-slug').value, image: $('content-image').value, video_url: $('content-url').value, category: $('content-category').value, year: $('content-year').value, description: $('content-description').value, published: $('content-published').checked ? 1 : 0 }; try { await api(id ? `/api/admin/content/${id}` : '/api/admin/content', { method: id ? 'PUT' : 'POST', body: JSON.stringify(payload) }); await loadContent(); await loadMetrics(); fillEditor(); setStatus('content-status', 'Saved.'); } catch (error) { setStatus('content-status', error.message, true); } };
    $('refresh-reviews').onclick = loadReviews;
    $('upload-form').onsubmit = async (event) => { event.preventDefault(); const file = $('upload-file').files[0]; if (!file) return; setStatus('upload-status', 'Uploading…'); const body = new FormData(); body.append('file', file); try { const data = await api('/api/admin/media', { method: 'POST', body }); setStatus('upload-status', `Uploaded ${data.key}`); await loadMetrics(); event.currentTarget.reset(); } catch (error) { setStatus('upload-status', error.message, true); } };
  });
})();
