const json = (body, status = 200, origin = '') => new Response(JSON.stringify(body), { status, headers: { 'content-type': 'application/json; charset=utf-8', 'cache-control': status >= 400 ? 'no-store' : 'public, max-age=30', 'access-control-allow-origin': origin || 'https://www.musfiqrfarhan.blog', 'access-control-allow-headers': 'Content-Type, Authorization', 'access-control-allow-methods': 'GET, POST, PUT, PATCH, DELETE, OPTIONS' } });
const text = (body, status = 200, type = 'text/plain; charset=utf-8') => new Response(body, { status, headers: { 'content-type': type, 'cache-control': 'public, max-age=3600' } });
const allowedOrigins = new Set(['https://www.musfiqrfarhan.blog', 'https://musfiqrfarhan.blog', 'https://bayzed123.github.io']);
const clean = (value, max = 1000) => String(value ?? '').trim().slice(0, max);
const slugify = (value) => clean(value, 180).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || `item-${Date.now()}`;
const originFor = (request) => { const origin = request.headers.get('Origin') || ''; return allowedOrigins.has(origin) ? origin : 'https://www.musfiqrfarhan.blog'; };
const responseHeaders = (origin) => ({ 'access-control-allow-origin': origin, 'access-control-allow-headers': 'Content-Type, Authorization', 'access-control-allow-methods': 'GET, POST, PUT, PATCH, DELETE, OPTIONS' });

function b64url(bytes) { let str = ''; if (typeof bytes === 'string') str = bytes; else { for (const byte of bytes) str += String.fromCharCode(byte); } return btoa(str).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, ''); }
function unb64url(value) { const padded = value.replace(/-/g, '+').replace(/_/g, '/') + '='.repeat((4 - value.length % 4) % 4); return atob(padded); }
async function hmac(secret, value) { const key = await crypto.subtle.importKey('raw', new TextEncoder().encode(secret), { name: 'HMAC', hash: 'SHA-256' }, false, ['sign', 'verify']); return crypto.subtle.sign('HMAC', key, new TextEncoder().encode(value)); }
async function makeToken(env, username) { const payload = b64url(JSON.stringify({ sub: username, exp: Date.now() + 1000 * 60 * 60 * 12 })); return `${payload}.${b64url(new Uint8Array(await hmac(env.ADMIN_PASSWORD, payload)))}`; }
async function requireAdmin(request, env) { const header = request.headers.get('Authorization') || ''; const token = header.replace(/^Bearer\s+/i, ''); const [payload, signature] = token.split('.'); if (!payload || !signature) return false; try { const data = JSON.parse(unb64url(payload)); if (!data.exp || data.exp < Date.now()) return false; const expected = new Uint8Array(await hmac(env.ADMIN_PASSWORD, payload)); const actual = Uint8Array.from(unb64url(signature), (char) => char.charCodeAt(0)); if (expected.length !== actual.length) return false; let same = 0; for (let i = 0; i < expected.length; i++) same |= expected[i] ^ actual[i]; return same === 0 && data.sub === env.ADMIN_USER_NAME; } catch { return false; } }
async function readJson(request) { try { return await request.json(); } catch { return {}; } }
function rowToContent(row) { return { ...row, published: Number(row.published) }; }
function mediaKeyFor(name) { const safe = clean(name, 180).replace(/[^a-zA-Z0-9._-]/g, '-'); return `${new Date().toISOString().slice(0, 10)}/${crypto.randomUUID()}-${safe || 'upload'}`; }
function normalizeContent(body) { const type = ['video','post','featured'].includes(body.type) ? body.type : ''; const title = clean(body.title, 160); const slug = slugify(body.slug || title); const image = clean(body.image, 600); const videoUrl = clean(body.video_url || body.url, 600); const attachmentUrl = clean(body.attachment_url, 600); const category = clean(body.category || body.tag, 80); const subcategory = clean(body.subcategory, 80); const description = clean(body.description || body.excerpt, 800); const seoTitle = clean(body.seo_title, 180); const metaDescription = clean(body.meta_description, 300); const keywords = clean(body.keywords, 500); const authorName = clean(body.author_name || 'Musfiq R. Farhan', 120); const canonicalUrl = clean(body.canonical_url || (type === 'featured' ? 'https://www.musfiqrfarhan.blog/' : `https://www.musfiqrfarhan.blog/${type === 'post' ? 'post' : 'watch'}.html?slug=${slug}`), 600); const published = body.published === 0 ? 0 : 1; const publishedAt = clean(body.published_at || new Date().toISOString(), 40); if (!type || !title) return { error: 'Content type and title are required.' }; if (published && (!seoTitle || !metaDescription || !canonicalUrl || !authorName || !category || !image || !publishedAt)) return { error: 'Published items require SEO title, meta description, canonical URL, author, category, image, and publish date.' }; if (published && type === 'video' && !videoUrl) return { error: 'Published videos require a YouTube or external video URL.' }; return { type, title, slug, image, videoUrl, attachmentUrl, category, subcategory, year: clean(body.year, 20), description, seoTitle, metaDescription, keywords, authorName, canonicalUrl, ogImage: clean(body.og_image || image, 600), body: clean(body.body, 10000), publishedAt, modifiedAt: new Date().toISOString(), duration: clean(body.duration, 40), embedUrl: clean(body.embed_url, 600), thumbnailUrl: clean(body.thumbnail_url || image, 600), indexable: body.indexable === 0 ? 0 : 1, published }; }

async function publicHome(env) {
  const featured = await env.DB.prepare("SELECT * FROM content WHERE type='featured' AND published=1 ORDER BY updated_at DESC LIMIT 1").first();
  const videos = await env.DB.prepare("SELECT * FROM content WHERE type='video' AND published=1 ORDER BY COALESCE(year, created_at) DESC, id DESC LIMIT 8").all();
  const posts = await env.DB.prepare("SELECT * FROM content WHERE type='post' AND published=1 ORDER BY COALESCE(year, created_at) DESC, id DESC LIMIT 6").all();
  return { featured: featured ? rowToContent(featured) : null, videos: videos.results.map(rowToContent), posts: posts.results.map(rowToContent) };
}
async function publicReviews(env, slug = '') { const query = slug ? 'SELECT name, rating, body, created_at FROM reviews WHERE approved=1 AND content_slug=? ORDER BY created_at DESC LIMIT 12' : 'SELECT name, rating, body, created_at FROM reviews WHERE approved=1 ORDER BY created_at DESC LIMIT 12'; const result = slug ? await env.DB.prepare(query).bind(slug).all() : await env.DB.prepare(query).all(); const rows = result.results; const average = rows.length ? rows.reduce((sum, row) => sum + Number(row.rating), 0) / rows.length : 0; return { reviews: rows, count: rows.length, average: Number(average.toFixed(1)) }; }
async function publicGallery(env) { const result = await env.DB.prepare('SELECT id, title, slug, image_url, alt_text, category, caption, sort_order FROM gallery WHERE published=1 ORDER BY sort_order ASC, updated_at DESC').all(); return { items: result.results }; }
async function adminMetrics(env) { const content = await env.DB.prepare('SELECT COUNT(*) AS count FROM content').first(); const media = await env.DB.prepare('SELECT COUNT(*) AS count FROM media').first(); const pending = await env.DB.prepare('SELECT COUNT(*) AS count FROM reviews WHERE approved=0').first(); const rating = await env.DB.prepare('SELECT AVG(rating) AS avg FROM reviews WHERE approved=1').first(); const mediaItems = await env.DB.prepare('SELECT object_key AS key, public_url AS url FROM media ORDER BY created_at DESC LIMIT 40').all(); return { content: Number(content?.count || 0), media: Number(media?.count || 0), pending_reviews: Number(pending?.count || 0), average_rating: Number(Number(rating?.avg || 0).toFixed(1)), media_items: mediaItems.results }; }

export default {
  async fetch(request, env) {
    const origin = originFor(request); const url = new URL(request.url); const path = url.pathname; const method = request.method;
    if (method === 'OPTIONS') return new Response(null, { status: 204, headers: responseHeaders(origin) });
    try {
      if (path === '/health') return json({ ok: true, service: 'MRF-API', time: new Date().toISOString() }, 200, origin);
      if (path === '/api/public/home' && method === 'GET') return json(await publicHome(env), 200, origin);
      if (path === '/api/public/gallery' && method === 'GET') return json(await publicGallery(env), 200, origin);
      if (path === '/api/public/category' && method === 'GET') { const category = clean(url.searchParams.get('category'), 80); const subcategory = clean(url.searchParams.get('subcategory'), 80); if (!category) return json({ error: 'Category is required.' }, 400, origin); const items = subcategory ? await env.DB.prepare('SELECT * FROM content WHERE published=1 AND category=? AND subcategory=? ORDER BY COALESCE(published_at, created_at) DESC, id DESC').bind(category, subcategory).all() : await env.DB.prepare('SELECT * FROM content WHERE published=1 AND category=? ORDER BY COALESCE(published_at, created_at) DESC, id DESC').bind(category).all(); const gallery = subcategory ? await env.DB.prepare('SELECT * FROM gallery WHERE published=1 AND category=? ORDER BY sort_order ASC, updated_at DESC').bind(category).all() : await env.DB.prepare('SELECT * FROM gallery WHERE published=1 AND category=? ORDER BY sort_order ASC, updated_at DESC').bind(category).all(); return json({ category, subcategory, items: items.results.map(rowToContent), gallery: gallery.results }, 200, origin); }
      if (path === '/api/public/sitemap' && method === 'GET') { const result = await env.DB.prepare("SELECT canonical_url AS loc, modified_at AS lastmod FROM content WHERE published=1 AND indexable=1 AND canonical_url IS NOT NULL ORDER BY modified_at DESC").all(); return json({ urls: result.results }, 200, origin); }
      const publicContentMatch = path.match(/^\/api\/public\/content\/([a-z0-9-]+)$/); if (publicContentMatch && method === 'GET') { const row = await env.DB.prepare('SELECT * FROM content WHERE slug=? AND published=1 LIMIT 1').bind(publicContentMatch[1]).first(); return row ? json(rowToContent(row), 200, origin) : json({ error: 'Content not found.' }, 404, origin); }
      if (path === '/api/public/reviews' && method === 'GET') return json(await publicReviews(env, clean(url.searchParams.get('slug'), 180)), 200, origin);
      if (path === '/api/public/reviews' && method === 'POST') { const body = await readJson(request); const name = clean(body.name, 80); const review = clean(body.body, 500); const rating = Number(body.rating); const contentSlug = clean(body.content_slug, 180) || null; if (!name || !review || !Number.isInteger(rating) || rating < 1 || rating > 5) return json({ error: 'Name, note, and a rating from 1 to 5 are required.' }, 400, origin); if (contentSlug) { const content = await env.DB.prepare('SELECT id FROM content WHERE slug=? AND published=1 LIMIT 1').bind(contentSlug).first(); if (!content) return json({ error: 'Content page not found.' }, 404, origin); } await env.DB.prepare('INSERT INTO reviews(name, rating, body, content_slug, approved) VALUES (?, ?, ?, ?, 0)').bind(name, rating, review, contentSlug).run(); return json({ ok: true, message: 'Review submitted for approval.' }, 201, origin); }
      if (path === '/api/admin/login' && method === 'POST') { const body = await readJson(request); if (!env.ADMIN_USER_NAME || !env.ADMIN_PASSWORD || body.username !== env.ADMIN_USER_NAME || body.password !== env.ADMIN_PASSWORD) return json({ error: 'Invalid credentials.' }, 401, origin); return json({ token: await makeToken(env, env.ADMIN_USER_NAME) }, 200, origin); }
      if (path.startsWith('/api/admin/')) { if (!(await requireAdmin(request, env))) return json({ error: 'Unauthorized.' }, 401, origin); }
      if (path === '/api/admin/content' && method === 'GET') { const result = await env.DB.prepare('SELECT * FROM content ORDER BY updated_at DESC, id DESC').all(); return json({ items: result.results.map(rowToContent) }, 200, origin); }
      if (path === '/api/admin/gallery' && method === 'GET') { const result = await env.DB.prepare('SELECT * FROM gallery ORDER BY sort_order ASC, updated_at DESC').all(); return json({ items: result.results }, 200, origin); }
      if (path === '/api/admin/gallery' && method === 'POST') { const body = await readJson(request); const title = clean(body.title, 160); const image = clean(body.image_url || body.image, 600); const alt = clean(body.alt_text || body.alt, 240); if (!title || !image || !alt) return json({ error: 'Title, image URL, and alt text are required.' }, 400, origin); const row = await env.DB.prepare('INSERT INTO gallery(title,slug,image_url,alt_text,category,caption,published,sort_order,updated_at) VALUES (?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP) RETURNING *').bind(title, slugify(body.slug || title), image, alt, clean(body.category, 80) || 'Archive', clean(body.caption, 240), body.published === 0 ? 0 : 1, Number(body.sort_order || 0)).first(); return json(row, 201, origin); }
      if (path === '/api/admin/content' && method === 'POST') { const body = await readJson(request); const normalized = normalizeContent(body); if (normalized.error) return json({ error: normalized.error }, 400, origin); const result = await env.DB.prepare('INSERT INTO content(type,title,slug,image,video_url,attachment_url,category,subcategory,year,description,seo_title,meta_description,keywords,author_name,canonical_url,og_image,body,published_at,modified_at,duration,embed_url,thumbnail_url,indexable,published,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP) RETURNING *').bind(normalized.type, normalized.title, normalized.slug, normalized.image, normalized.videoUrl, normalized.attachmentUrl, normalized.category, normalized.subcategory, normalized.year, normalized.description, normalized.seoTitle, normalized.metaDescription, normalized.keywords, normalized.authorName, normalized.canonicalUrl, normalized.ogImage, normalized.body, normalized.publishedAt, normalized.modifiedAt, normalized.duration, normalized.embedUrl, normalized.thumbnailUrl, normalized.indexable, normalized.published).first(); return json(rowToContent(result), 201, origin); }
      const galleryMatch = path.match(/^\/api\/admin\/gallery\/(\d+)$/); if (galleryMatch) { const id = Number(galleryMatch[1]); if (method === 'DELETE') { await env.DB.prepare('DELETE FROM gallery WHERE id=?').bind(id).run(); return json({ ok: true }, 200, origin); } if (method === 'PATCH') { const body = await readJson(request); const title = clean(body.title, 160); const image = clean(body.image_url || body.image, 600); const alt = clean(body.alt_text || body.alt, 240); if (!title || !image || !alt) return json({ error: 'Title, image URL, and alt text are required.' }, 400, origin); const row = await env.DB.prepare('UPDATE gallery SET title=?, slug=?, image_url=?, alt_text=?, category=?, caption=?, published=?, sort_order=?, updated_at=CURRENT_TIMESTAMP WHERE id=? RETURNING *').bind(title, slugify(body.slug || title), image, alt, clean(body.category, 80) || 'Archive', clean(body.caption, 240), body.published === 0 ? 0 : 1, Number(body.sort_order || 0), id).first(); return row ? json(row, 200, origin) : json({ error: 'Gallery item not found.' }, 404, origin); } }
      const contentMatch = path.match(/^\/api\/admin\/content\/(\d+)$/); if (contentMatch) { const id = Number(contentMatch[1]); if (method === 'DELETE') { await env.DB.prepare('DELETE FROM content WHERE id=?').bind(id).run(); return json({ ok: true }, 200, origin); } if (method === 'PUT') { const body = await readJson(request); const normalized = normalizeContent(body); if (normalized.error) return json({ error: normalized.error }, 400, origin); const current = await env.DB.prepare('SELECT slug FROM content WHERE id=?').bind(id).first(); if (!current) return json({ error: 'Content not found.' }, 404, origin); normalized.slug = current.slug; const result = await env.DB.prepare('UPDATE content SET type=?, title=?, slug=?, image=?, video_url=?, attachment_url=?, category=?, subcategory=?, year=?, description=?, seo_title=?, meta_description=?, keywords=?, author_name=?, canonical_url=?, og_image=?, body=?, published_at=?, modified_at=?, duration=?, embed_url=?, thumbnail_url=?, indexable=?, published=?, updated_at=CURRENT_TIMESTAMP WHERE id=? RETURNING *').bind(normalized.type, normalized.title, normalized.slug, normalized.image, normalized.videoUrl, normalized.attachmentUrl, normalized.category, normalized.subcategory, normalized.year, normalized.description, normalized.seoTitle, normalized.metaDescription, normalized.keywords, normalized.authorName, normalized.canonicalUrl, normalized.ogImage, normalized.body, normalized.publishedAt, normalized.modifiedAt, normalized.duration, normalized.embedUrl, normalized.thumbnailUrl, normalized.indexable, normalized.published, id).first(); return result ? json(rowToContent(result), 200, origin) : json({ error: 'Content not found.' }, 404, origin); } }
      if (path === '/api/admin/reviews' && method === 'GET') { const result = await env.DB.prepare('SELECT * FROM reviews ORDER BY approved ASC, created_at DESC').all(); return json({ reviews: result.results }, 200, origin); }
      const reviewMatch = path.match(/^\/api\/admin\/reviews\/(\d+)$/); if (reviewMatch && method === 'PATCH') { const body = await readJson(request); await env.DB.prepare('UPDATE reviews SET approved=? WHERE id=?').bind(body.approved ? 1 : 0, Number(reviewMatch[1])).run(); return json({ ok: true }, 200, origin); }
      if (path === '/api/admin/metrics' && method === 'GET') { const metrics = await adminMetrics(env); const gallery = await env.DB.prepare('SELECT COUNT(*) AS count FROM gallery').first(); return json({ ...metrics, gallery: Number(gallery?.count || 0) }, 200, origin); }
      if (path === '/api/admin/media' && method === 'POST') { const form = await request.formData(); const file = form.get('file'); if (!(file instanceof File)) return json({ error: 'A file is required.' }, 400, origin); const max = 250 * 1024 * 1024; if (file.size > max) return json({ error: 'Files must be 250 MB or smaller.' }, 413, origin); const key = mediaKeyFor(file.name); await env.MEDIA.put(key, file.stream(), { httpMetadata: { contentType: file.type || 'application/octet-stream', contentDisposition: `inline; filename="${clean(file.name, 120)}"` } }); const publicUrl = `${url.origin}/media/${key}`; await env.DB.prepare('INSERT INTO media(object_key,original_name,content_type,size,public_url) VALUES(?,?,?,?,?)').bind(key, clean(file.name, 180), file.type || 'application/octet-stream', file.size, publicUrl).run(); return json({ ok: true, key, url: publicUrl }, 201, origin); }
      if (path.startsWith('/media/') && method === 'GET') { const key = decodeURIComponent(path.slice('/media/'.length)); const object = await env.MEDIA.get(key); if (!object) return text('Not found', 404); const headers = new Headers(); object.writeHttpMetadata(headers); headers.set('etag', object.httpEtag); headers.set('cache-control', 'public, max-age=31536000, immutable'); return new Response(object.body, { headers }); }
      return json({ error: 'Not found.' }, 404, origin);
    } catch (error) { console.error(error); return json({ error: 'Unexpected API error.' }, 500, origin); }
  }
};
