const json = (body, status = 200, origin = '') => new Response(JSON.stringify(body), { status, headers: { 'content-type': 'application/json; charset=utf-8', 'cache-control': status >= 400 ? 'no-store' : 'public, max-age=30', 'access-control-allow-origin': origin || 'https://www.musfiqrfarhan.blog', 'access-control-allow-headers': 'Content-Type, Authorization', 'access-control-allow-methods': 'GET, POST, PUT, PATCH, DELETE, OPTIONS' } });
const text = (body, status = 200, type = 'text/plain; charset=utf-8') => new Response(body, { status, headers: { 'content-type': type, 'cache-control': 'public, max-age=3600' } });
const allowedOrigins = new Set(['https://www.musfiqrfarhan.blog', 'https://musfiqrfarhan.blog', 'https://bayzed123.github.io']);
const clean = (value, max = 1000) => String(value ?? '').trim().slice(0, max);
const slugify = (value) => clean(value, 180).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || `item-${Date.now()}`;
const originFor = (request) => { const origin = request.headers.get('Origin') || ''; return allowedOrigins.has(origin) ? origin : 'https://www.musfiqrfarhan.blog'; };
const responseHeaders = (origin) => ({ 'access-control-allow-origin': origin, 'access-control-allow-headers': 'Content-Type, Authorization', 'access-control-allow-methods': 'GET, POST, PUT, PATCH, DELETE, OPTIONS' });

function b64url(bytes) { let str = ''; if (typeof bytes === 'string') str = bytes; else { for (const byte of bytes) str += String.fromCharCode(byte); } return btoa(str).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, ''); }
function unb64url(value) { const padded = value.replace(/-/g, '+').replace(/_/g, '/') + '='.repeat((4 - value.length % 4) % 4); return atob(padded); }
async function hmac(secret, value) { const key = await crypto.subtle.importKey('raw', new TextEncoder().encode(secret), { name: 'HMAC', hash: 'SHA-256' }, false, ['sign', 'verify']); return crypto.subtle.sign('HMAC', key, new TextEncoder().encode(value)); }
async function makeToken(env, username) { const payload = b64url(JSON.stringify({ sub: username, exp: Date.now() + 1000 * 60 * 60 * 12 })); return `${payload}.${b64url(new Uint8Array(await hmac(env.ADMIN_PASSWORD, payload)))}`; }
async function requireAdmin(request, env) { const header = request.headers.get('Authorization') || ''; const token = header.replace(/^Bearer\s+/i, ''); const [payload, signature] = token.split('.'); if (!payload || !signature) return false; try { const data = JSON.parse(unb64url(payload)); if (!data.exp || data.exp < Date.now()) return false; const expected = new Uint8Array(await hmac(env.ADMIN_PASSWORD, payload)); const actual = Uint8Array.from(unb64url(signature), (char) => char.charCodeAt(0)); if (expected.length !== actual.length) return false; let same = 0; for (let i = 0; i < expected.length; i++) same |= expected[i] ^ actual[i]; return same === 0 && data.sub === env.ADMIN_USER_NAME; } catch { return false; } }
async function readJson(request) { try { return await request.json(); } catch { return {}; } }
function rowToContent(row) { return { ...row, published: Number(row.published) }; }
function mediaKeyFor(name) { const safe = clean(name, 180).replace(/[^a-zA-Z0-9._-]/g, '-'); return `${new Date().toISOString().slice(0, 10)}/${crypto.randomUUID()}-${safe || 'upload'}`; }

async function publicHome(env) {
  const featured = await env.DB.prepare("SELECT * FROM content WHERE type='featured' AND published=1 ORDER BY updated_at DESC LIMIT 1").first();
  const videos = await env.DB.prepare("SELECT * FROM content WHERE type='video' AND published=1 ORDER BY COALESCE(year, created_at) DESC, id DESC LIMIT 8").all();
  const posts = await env.DB.prepare("SELECT * FROM content WHERE type='post' AND published=1 ORDER BY COALESCE(year, created_at) DESC, id DESC LIMIT 6").all();
  return { featured: featured ? rowToContent(featured) : null, videos: videos.results.map(rowToContent), posts: posts.results.map(rowToContent) };
}
async function publicReviews(env) { const result = await env.DB.prepare('SELECT name, rating, body, created_at FROM reviews WHERE approved=1 ORDER BY created_at DESC LIMIT 12').all(); const rows = result.results; const average = rows.length ? rows.reduce((sum, row) => sum + Number(row.rating), 0) / rows.length : 0; return { reviews: rows, count: rows.length, average: Number(average.toFixed(1)) }; }
async function adminMetrics(env) { const content = await env.DB.prepare('SELECT COUNT(*) AS count FROM content').first(); const media = await env.DB.prepare('SELECT COUNT(*) AS count FROM media').first(); const pending = await env.DB.prepare('SELECT COUNT(*) AS count FROM reviews WHERE approved=0').first(); const rating = await env.DB.prepare('SELECT AVG(rating) AS avg FROM reviews WHERE approved=1').first(); const mediaItems = await env.DB.prepare('SELECT object_key AS key, public_url AS url FROM media ORDER BY created_at DESC LIMIT 40').all(); return { content: Number(content?.count || 0), media: Number(media?.count || 0), pending_reviews: Number(pending?.count || 0), average_rating: Number(Number(rating?.avg || 0).toFixed(1)), media_items: mediaItems.results }; }

export default {
  async fetch(request, env) {
    const origin = originFor(request); const url = new URL(request.url); const path = url.pathname; const method = request.method;
    if (method === 'OPTIONS') return new Response(null, { status: 204, headers: responseHeaders(origin) });
    try {
      if (path === '/health') return json({ ok: true, service: 'MRF-API', time: new Date().toISOString() }, 200, origin);
      if (path === '/api/public/home' && method === 'GET') return json(await publicHome(env), 200, origin);
      if (path === '/api/public/reviews' && method === 'GET') return json(await publicReviews(env), 200, origin);
      if (path === '/api/public/reviews' && method === 'POST') { const body = await readJson(request); const name = clean(body.name, 80); const review = clean(body.body, 500); const rating = Number(body.rating); if (!name || !review || !Number.isInteger(rating) || rating < 1 || rating > 5) return json({ error: 'Name, note, and a rating from 1 to 5 are required.' }, 400, origin); await env.DB.prepare('INSERT INTO reviews(name, rating, body, approved) VALUES (?, ?, ?, 0)').bind(name, rating, review).run(); return json({ ok: true, message: 'Review submitted for approval.' }, 201, origin); }
      if (path === '/api/admin/login' && method === 'POST') { const body = await readJson(request); if (!env.ADMIN_USER_NAME || !env.ADMIN_PASSWORD || body.username !== env.ADMIN_USER_NAME || body.password !== env.ADMIN_PASSWORD) return json({ error: 'Invalid credentials.' }, 401, origin); return json({ token: await makeToken(env, env.ADMIN_USER_NAME) }, 200, origin); }
      if (path.startsWith('/api/admin/')) { if (!(await requireAdmin(request, env))) return json({ error: 'Unauthorized.' }, 401, origin); }
      if (path === '/api/admin/content' && method === 'GET') { const result = await env.DB.prepare('SELECT * FROM content ORDER BY updated_at DESC, id DESC').all(); return json({ items: result.results.map(rowToContent) }, 200, origin); }
      if (path === '/api/admin/content' && method === 'POST') { const body = await readJson(request); const title = clean(body.title, 160); if (!title || !['video', 'post', 'featured'].includes(body.type)) return json({ error: 'Type and title are required.' }, 400, origin); const slug = slugify(body.slug || title); const result = await env.DB.prepare('INSERT INTO content(type,title,slug,image,video_url,category,year,description,published,updated_at) VALUES (?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP) RETURNING *').bind(body.type, title, slug, clean(body.image, 600), clean(body.video_url || body.url, 600), clean(body.category || body.tag, 80), clean(body.year, 20), clean(body.description || body.excerpt, 800), body.published === 0 ? 0 : 1).first(); return json(rowToContent(result), 201, origin); }
      const contentMatch = path.match(/^\/api\/admin\/content\/(\d+)$/); if (contentMatch) { const id = Number(contentMatch[1]); if (method === 'DELETE') { await env.DB.prepare('DELETE FROM content WHERE id=?').bind(id).run(); return json({ ok: true }, 200, origin); } if (method === 'PUT') { const body = await readJson(request); const title = clean(body.title, 160); if (!title) return json({ error: 'Title is required.' }, 400, origin); const result = await env.DB.prepare('UPDATE content SET type=?, title=?, slug=?, image=?, video_url=?, category=?, year=?, description=?, published=?, updated_at=CURRENT_TIMESTAMP WHERE id=? RETURNING *').bind(body.type, title, slugify(body.slug || title), clean(body.image, 600), clean(body.video_url || body.url, 600), clean(body.category || body.tag, 80), clean(body.year, 20), clean(body.description || body.excerpt, 800), body.published === 0 ? 0 : 1, id).first(); return result ? json(rowToContent(result), 200, origin) : json({ error: 'Content not found.' }, 404, origin); } }
      if (path === '/api/admin/reviews' && method === 'GET') { const result = await env.DB.prepare('SELECT * FROM reviews ORDER BY approved ASC, created_at DESC').all(); return json({ reviews: result.results }, 200, origin); }
      const reviewMatch = path.match(/^\/api\/admin\/reviews\/(\d+)$/); if (reviewMatch && method === 'PATCH') { const body = await readJson(request); await env.DB.prepare('UPDATE reviews SET approved=? WHERE id=?').bind(body.approved ? 1 : 0, Number(reviewMatch[1])).run(); return json({ ok: true }, 200, origin); }
      if (path === '/api/admin/metrics' && method === 'GET') return json(await adminMetrics(env), 200, origin);
      if (path === '/api/admin/media' && method === 'POST') { const form = await request.formData(); const file = form.get('file'); if (!(file instanceof File)) return json({ error: 'A file is required.' }, 400, origin); const max = 250 * 1024 * 1024; if (file.size > max) return json({ error: 'Files must be 250 MB or smaller.' }, 413, origin); const key = mediaKeyFor(file.name); await env.MEDIA.put(key, file.stream(), { httpMetadata: { contentType: file.type || 'application/octet-stream', contentDisposition: `inline; filename="${clean(file.name, 120)}"` } }); const publicUrl = `${url.origin}/media/${key}`; await env.DB.prepare('INSERT INTO media(object_key,original_name,content_type,size,public_url) VALUES(?,?,?,?,?)').bind(key, clean(file.name, 180), file.type || 'application/octet-stream', file.size, publicUrl).run(); return json({ ok: true, key, url: publicUrl }, 201, origin); }
      if (path.startsWith('/media/') && method === 'GET') { const key = decodeURIComponent(path.slice('/media/'.length)); const object = await env.MEDIA.get(key); if (!object) return text('Not found', 404); const headers = new Headers(); object.writeHttpMetadata(headers); headers.set('etag', object.httpEtag); headers.set('cache-control', 'public, max-age=31536000, immutable'); return new Response(object.body, { headers }); }
      return json({ error: 'Not found.' }, 404, origin);
    } catch (error) { console.error(error); return json({ error: 'Unexpected API error.' }, 500, origin); }
  }
};
